baseurl = "https://www.example.com/"
title = "Test Git Info"
author = "Antoine"
canonifyurls = true
languagecode = "en"
theme = "black-and-light"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Test Git Info"
  disableWebFonts = false

enableGitInfo = "true"

[[menu.main]]
    name = "About"
    url  = "/about"
[[menu.main]]
    name = "Projects"
    url  = "https://github.com/davidhampgonsalves/hugo-black-and-light-theme"
[[menu.main]]
    name = "Resume"
    url  = "https://github.com/davidhampgonsalves/hugo-black-and-light-theme"
